/* ======================================
   BASE DE CONOCIMIENTO VLADISYSTEMS
   Archivo: glosario-data.js
   ====================================== */


const GLOSARIO = [
  {
    "TÉRMINO": "Agente inmobiliario",
    "DEFINICIÓN": "Profesional que actúa como intermediario entre compradores y vendedores de bienes raíces. Asesora, negocia, gestiona documentación y cierra transacciones de propiedades.",
    "CARACTERÍSTICAS": "Orientado a resultados comerciales; requiere conocimiento del mercado local, habilidades de negociación y manejo de clientes. Limitación: depende del ciclo económico y de la oferta disponible.",
    "ENTORNO": "Sector inmobiliario, bienes raíces",
    "ENTRADA / PROCESO / SALIDA": "Proceso (gestión de compraventa)",
    "TRADUCCIÓN / EQUIVALENCIA": "Real estate agent / Real estate broker",
    "EJEMPLOS": "Portal33, BC1166",
    "CATEGORÍA": "Perfil Profesional",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Analista de programación",
    "DEFINICIÓN": "Profesional técnico que diseña la lógica de un sistema informático: define flujos de datos, estructuras de archivos, procesos batch y reglas de negocio antes de que el programador codifique.",
    "CARACTERÍSTICAS": "Orientado a sistemas legacy; traduce requerimientos de negocio a especificaciones técnicas. Fuerte en análisis lógico y diagramas de flujo. Limitación: perfil que requiere actualización constante ante nuevas tecnologías.",
    "ENTORNO": "Sistemas informáticos, TI, desarrollo de software",
    "ENTRADA / PROCESO / SALIDA": "Proceso (diseño y análisis de sistemas)",
    "TRADUCCIÓN / EQUIVALENCIA": "Systems analyst / Programming analyst",
    "EJEMPLOS": "COBOL, sistemas bancarios legacy",
    "CATEGORÍA": "Perfil Profesional",
    "NIVEL TÉCNICO": "Avanzado"
  },
  {
    "TÉRMINO": "Analista de sistemas",
    "DEFINICIÓN": "Profesional que estudia, diseña y evalúa sistemas de información. Identifica necesidades del negocio y propone soluciones tecnológicas, actuando como puente entre usuarios y desarrolladores.",
    "CARACTERÍSTICAS": "Perfil híbrido: técnico y comunicativo. Domina modelado de datos, diagramas UML y análisis de requerimientos. Limitación: si no se actualiza, puede quedar obsoleto ante arquitecturas modernas.",
    "ENTORNO": "TI, desarrollo de software, consultoría tecnológica",
    "ENTRADA / PROCESO / SALIDA": "Proceso (análisis y diseño)",
    "TRADUCCIÓN / EQUIVALENCIA": "Systems analyst",
    "EJEMPLOS": "Análisis de sistemas COBOL, diseño de VladCRM",
    "CATEGORÍA": "Perfil Profesional",
    "NIVEL TÉCNICO": "Avanzado"
  },
  {
    "TÉRMINO": "Arquitectura digital",
    "DEFINICIÓN": "Estructura organizacional y técnica que define cómo se construyen, conectan y se comunican los distintos componentes de un sistema digital: bases de datos, APIs, interfaces, servidores y servicios.",
    "CARACTERÍSTICAS": "Garantiza escalabilidad, mantenibilidad y coherencia del sistema. Permite visualizar el sistema completo antes de construirlo. Limitación: un mal diseño inicial es muy costoso de corregir en producción.",
    "ENTORNO": "Ingeniería de software, DevOps, plataformas digitales",
    "ENTRADA / PROCESO / SALIDA": "Proceso (diseño de sistema)",
    "TRADUCCIÓN / EQUIVALENCIA": "Digital architecture / System architecture",
    "EJEMPLOS": "Arquitectura de Vladisystems Portfolio (HTML + CSS + JS)",
    "CATEGORÍA": "Tecnología Web",
    "NIVEL TÉCNICO": "Avanzado"
  },
  {
    "TÉRMINO": "Automatización",
    "DEFINICIÓN": "Ejecución de tareas o procesos mediante lógica programada, sin intervención manual continua. Un sistema automatizado recibe una condición o evento y responde ejecutando acciones predefinidas.",
    "CARACTERÍSTICAS": "Reduce errores humanos, ahorra tiempo y permite escalar operaciones. Puede ejecutarse 24/7. Limitación: requiere mantenimiento ante cambios en las condiciones del entorno y puede fallar si las reglas no están bien definidas.",
    "ENTORNO": "Software, DevOps, marketing digital, CRM",
    "ENTRADA / PROCESO / SALIDA": "Proceso (ejecución automática)",
    "TRADUCCIÓN / EQUIVALENCIA": "Automation / Process automation",
    "EJEMPLOS": "Telegram Bot Vladiblues, flujos de WhatsApp automáticos",
    "CATEGORÍA": "Tecnología Web",
    "NIVEL TÉCNICO": "Intermedio"
  },
  {
    "TÉRMINO": "BC1166 Remodelaciones",
    "DEFINICIÓN": "Sistema web de captación de clientes para empresa de remodelaciones. Diseñado para convertir visitantes en leads directos a través de WhatsApp, con presentación de servicios y llamadas a la acción.",
    "CARACTERÍSTICAS": "Enfocado en conversión comercial directa. Diseño limpio y orientado a acción. Limitación: no tiene backend propio; depende de WhatsApp como canal de cierre.",
    "ENTORNO": "Inmobiliario, construcción, marketing digital",
    "ENTRADA / PROCESO / SALIDA": "Proceso (captación de leads) → Salida (contacto comercial)",
    "TRADUCCIÓN / EQUIVALENCIA": "BC1166 Remodeling System",
    "EJEMPLOS": "Proyecto del portfolio Vladisystems",
    "CATEGORÍA": "Proyectos",
    "NIVEL TÉCNICO": "Intermedio"
  },
  {
    "TÉRMINO": "Bogotá",
    "DEFINICIÓN": "Ciudad capital de Colombia y contexto geográfico principal de operación de Vladisystems. Define el mercado local, zona horaria (UTC-5), idioma (español) y contexto cultural del trabajo.",
    "CARACTERÍSTICAS": "Referencia de ubicación para SEO local, clientes presenciales y contexto laboral híbrido. Limitación: limita visibilidad en búsquedas internacionales si no se complementa con estrategia global.",
    "ENTORNO": "Geografía, SEO local, trabajo",
    "ENTRADA / PROCESO / SALIDA": "Entorno",
    "TRADUCCIÓN / EQUIVALENCIA": "Bogotá (ciudad) / Colombia",
    "EJEMPLOS": "Vladisystems, Portal33, BC1166",
    "CATEGORÍA": "Perfil Profesional",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Botón",
    "DEFINICIÓN": "Elemento interactivo de la interfaz de usuario (UI) que desencadena una acción al ser clickeado o tocado. Puede ejecutar navegación, envío de formularios, apertura de modales o llamadas a la acción (CTA).",
    "CARACTERÍSTICAS": "Elemento fundamental de UI. Debe ser visualmente destacado, con estado hover/active y texto claro. Limitación: si no tiene contraste suficiente o feedback visual, los usuarios no saben si funcionó.",
    "ENTORNO": "UI, diseño web, frontend",
    "ENTRADA / PROCESO / SALIDA": "Entrada (acción del usuario)",
    "TRADUCCIÓN / EQUIVALENCIA": "Button / CTA (Call to Action)",
    "EJEMPLOS": "Botones WhatsApp en BC1166, CTA en páginas de proyectos",
    "CATEGORÍA": "UI / UX",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Captación de clientes",
    "DEFINICIÓN": "Proceso comercial orientado a atraer y convertir usuarios o visitantes en clientes potenciales (leads). Incluye estrategias de marketing digital, landing pages, formularios y canales de contacto directos.",
    "CARACTERÍSTICAS": "Proceso esencial para cualquier negocio digital. Combina diseño persuasivo, SEO y canales de comunicación. Limitación: sin seguimiento (CRM), los leads captados se pierden.",
    "ENTORNO": "Marketing digital, CRM, ventas",
    "ENTRADA / PROCESO / SALIDA": "Proceso (atracción y conversión)",
    "TRADUCCIÓN / EQUIVALENCIA": "Customer acquisition / Lead generation",
    "EJEMPLOS": "BC1166, Portal33, WhatsApp",
    "CATEGORÍA": "Negocio / CRM",
    "NIVEL TÉCNICO": "Intermedio"
  },
  {
    "TÉRMINO": "CDN",
    "DEFINICIÓN": "Red de servidores distribuidos geográficamente que almacena copias en caché del contenido web para entregarlo al usuario desde el servidor más cercano a su ubicación física, reduciendo la latencia.",
    "CARACTERÍSTICAS": "Mejora drásticamente la velocidad de carga, reduce la carga del servidor de origen y soporta picos de tráfico. Limitación: tiene costo elevado para proyectos pequeños; no optimiza contenido dinámico o personalizado en tiempo real.",
    "ENTORNO": "Web global, infraestructura de internet, performance",
    "ENTRADA / PROCESO / SALIDA": "Proceso (entrega de contenido)",
    "TRADUCCIÓN / EQUIVALENCIA": "Content Delivery Network / Red de distribución de contenido",
    "EJEMPLOS": "Scripts externos en el portfolio (cdnjs.cloudflare.com)",
    "CATEGORÍA": "Tecnología Web",
    "NIVEL TÉCNICO": "Avanzado"
  },
  {
    "TÉRMINO": "Contacto",
    "DEFINICIÓN": "Sección o canal del sitio web que permite al visitante comunicarse directamente con el propietario. Puede ser un formulario, un botón de WhatsApp, email o enlace a redes sociales.",
    "CARACTERÍSTICAS": "Elemento crítico de conversión. Debe ser accesible desde cualquier página. Limitación: sin integración a CRM, los mensajes se gestionan manualmente y se pueden perder.",
    "ENTORNO": "Web UI, marketing, ventas",
    "ENTRADA / PROCESO / SALIDA": "Entrada (inicio de comunicación comercial)",
    "TRADUCCIÓN / EQUIVALENCIA": "Contact / Contact section",
    "EJEMPLOS": "Botón WhatsApp en el footer de Vladisystems",
    "CATEGORÍA": "UI / UX",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Coordinador de servicios",
    "DEFINICIÓN": "Profesional que organiza, planifica y supervisa la ejecución de trabajos o proyectos de servicio. Gestiona tiempos, recursos humanos y comunicación entre equipos y clientes.",
    "CARACTERÍSTICAS": "Rol orientado a operaciones y gestión. Requiere habilidades de planificación y comunicación. Limitación: sin herramientas digitales de gestión, la coordinación se vuelve ineficiente a escala.",
    "ENTORNO": "Construcción, operaciones, gestión de proyectos",
    "ENTRADA / PROCESO / SALIDA": "Proceso (gestión operativa)",
    "TRADUCCIÓN / EQUIVALENCIA": "Services coordinator",
    "EJEMPLOS": "Proyectos de construcción y remodelación",
    "CATEGORÍA": "Perfil Profesional",
    "NIVEL TÉCNICO": "Intermedio"
  },
  {
    "TÉRMINO": "Credenciales",
    "DEFINICIÓN": "Certificaciones, títulos académicos o constancias que validan las competencias y formación profesional de una persona. En contexto digital pueden presentarse como documentos descargables o secciones de perfil.",
    "CARACTERÍSTICAS": "Generan confianza y credibilidad ante clientes y empleadores. Limitación: su valor depende del reconocimiento de la institución emisora y de la actualización constante.",
    "ENTORNO": "Educación, recursos humanos, perfil profesional",
    "ENTRADA / PROCESO / SALIDA": "Salida (validación profesional)",
    "TRADUCCIÓN / EQUIVALENCIA": "Credentials / Certifications",
    "EJEMPLOS": "CV Profesional, sección de credenciales del portfolio",
    "CATEGORÍA": "Plataformas y Servicios",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "CRM",
    "DEFINICIÓN": "Conjunto de estrategias, procesos y tecnologías que una empresa utiliza para gestionar, analizar y optimizar sus interacciones con clientes actuales y potenciales a lo largo de todo su ciclo de vida.",
    "CARACTERÍSTICAS": "Centraliza datos de clientes, automatiza seguimiento y mejora la tasa de conversión de ventas. Aumenta la retención y fidelización. Limitación: sin datos limpios y actualizados, se convierte en una base de datos inútil; requiere disciplina de uso.",
    "ENTORNO": "Negocios, ventas, marketing digital",
    "ENTRADA / PROCESO / SALIDA": "Proceso (gestión de relaciones comerciales)",
    "TRADUCCIÓN / EQUIVALENCIA": "Customer Relationship Management / Gestión de Relación con el Cliente",
    "EJEMPLOS": "VladCRM (sistema propio de Vladisystems)",
    "CATEGORÍA": "Negocio / CRM",
    "NIVEL TÉCNICO": "Intermedio"
  },
  {
    "TÉRMINO": "CV Profesional",
    "DEFINICIÓN": "Documento digital o físico que resume la trayectoria profesional, habilidades, estudios y logros de una persona. En entornos digitales puede presentarse como PDF descargable o página web.",
    "CARACTERÍSTICAS": "Primer punto de contacto formal en procesos de selección. Debe ser claro, actualizado y adaptado al perfil del receptor. Limitación: un CV estático puede no reflejar habilidades técnicas en tiempo real; el portfolio complementa este gap.",
    "ENTORNO": "Recursos humanos, perfil profesional, networking",
    "ENTRADA / PROCESO / SALIDA": "Salida (presentación profesional)",
    "TRADUCCIÓN / EQUIVALENCIA": "Curriculum Vitae / Professional resume",
    "EJEMPLOS": "PDF descargable en el portfolio Vladisystems",
    "CATEGORÍA": "Plataformas y Servicios",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Dashboard",
    "DEFINICIÓN": "Panel visual centralizado que presenta datos, métricas e indicadores clave de rendimiento (KPIs) de forma gráfica e interactiva, permitiendo monitoreo y toma de decisiones en tiempo real.",
    "CARACTERÍSTICAS": "Convierte datos complejos en visualizaciones comprensibles. Permite filtrar, comparar y analizar tendencias. Limitación: si los datos de origen son incorrectos o están desactualizados, el dashboard muestra información errónea.",
    "ENTORNO": "Business intelligence, sistemas, data analytics",
    "ENTRADA / PROCESO / SALIDA": "Proceso (visualización) → Salida (información para decisiones)",
    "TRADUCCIÓN / EQUIVALENCIA": "Dashboard / Panel de control",
    "EJEMPLOS": "Dashboard de Ventas 2025 (Looker Studio)",
    "CATEGORÍA": "Proyectos",
    "NIVEL TÉCNICO": "Intermedio"
  },
  {
    "TÉRMINO": "Data Analytics",
    "DEFINICIÓN": "Proceso de examinar, limpiar, transformar e interpretar conjuntos de datos con el objetivo de descubrir patrones útiles, extraer conclusiones y apoyar la toma de decisiones estratégicas.",
    "CARACTERÍSTICAS": "Combina estadística, programación y conocimiento de negocio. Permite anticipar tendencias. Limitación: requiere datos de calidad y volumen suficiente; sin ello, los resultados son poco confiables.",
    "ENTORNO": "Business intelligence, negocios, tecnología",
    "ENTRADA / PROCESO / SALIDA": "Proceso (análisis) → Salida (insights)",
    "TRADUCCIÓN / EQUIVALENCIA": "Data analytics / Análisis de datos",
    "EJEMPLOS": "Dashboard de Ventas 2025",
    "CATEGORÍA": "Tecnología Web",
    "NIVEL TÉCNICO": "Avanzado"
  },
  {
    "TÉRMINO": "Deploy",
    "DEFINICIÓN": "Proceso de publicar o lanzar un sistema, aplicación o sitio web desde un entorno de desarrollo o pruebas hacia el entorno de producción, donde queda disponible para los usuarios finales.",
    "CARACTERÍSTICAS": "Paso crítico en el ciclo de vida del software. Puede ser manual o automatizado (CI/CD). Limitación: un deploy sin pruebas previas puede romper el sistema en producción y afectar a usuarios reales.",
    "ENTORNO": "DevOps, desarrollo web, infraestructura",
    "ENTRADA / PROCESO / SALIDA": "Salida (sistema en producción)",
    "TRADUCCIÓN / EQUIVALENCIA": "Deploy / Deployment / Publicación en producción",
    "EJEMPLOS": "Deploy del portfolio en Netlify",
    "CATEGORÍA": "Tecnología Web",
    "NIVEL TÉCNICO": "Intermedio"
  },
  {
    "TÉRMINO": "Desarrollador web",
    "DEFINICIÓN": "Profesional que construye sitios y aplicaciones web. Puede especializarse en frontend (interfaces), backend (servidores/bases de datos) o ser fullstack (ambos).",
    "CARACTERÍSTICAS": "Perfil técnico con alta demanda. Combina conocimiento de lenguajes de programación, frameworks y diseño. Limitación: la especialización estrecha puede limitar la empleabilidad en proyectos pequeños que requieren versatilidad.",
    "ENTORNO": "Software, tecnología, empresas digitales",
    "ENTRADA / PROCESO / SALIDA": "Proceso (construcción de sistemas)",
    "TRADUCCIÓN / EQUIVALENCIA": "Web developer / Frontend developer / Fullstack developer",
    "EJEMPLOS": "Vladisystems como desarrollador web propio",
    "CATEGORÍA": "Perfil Profesional",
    "NIVEL TÉCNICO": "Intermedio"
  },
  {
    "TÉRMINO": "Desarrollo web",
    "DEFINICIÓN": "Proceso de creación, diseño y mantenimiento de sitios y aplicaciones accesibles a través de un navegador web. Incluye el trabajo de frontend (lo que el usuario ve) y backend (la lógica del servidor).",
    "CARACTERÍSTICAS": "Disciplina amplia que combina diseño visual, programación y experiencia de usuario. Alta demanda laboral. Limitación: tecnologías cambian rápidamente; requiere actualización constante.",
    "ENTORNO": "Tecnología, software, internet",
    "ENTRADA / PROCESO / SALIDA": "Proceso (creación y mantenimiento)",
    "TRADUCCIÓN / EQUIVALENCIA": "Web development / Desarrollo web",
    "EJEMPLOS": "Portfolio Vladisystems, BC1166, Portal33",
    "CATEGORÍA": "Tecnología Web",
    "NIVEL TÉCNICO": "Intermedio"
  },
  {
    "TÉRMINO": "Disponible",
    "DEFINICIÓN": "Estado laboral que indica que una persona está activa en búsqueda de empleo, proyectos freelance o colaboraciones. En LinkedIn se muestra como una señal visible para reclutadores.",
    "CARACTERÍSTICAS": "Aumenta la visibilidad en búsquedas de talento. Limitación: si no se actualiza el estado, puede generar confusión o pérdida de oportunidades.",
    "ENTORNO": "Empleo, networking profesional, LinkedIn",
    "ENTRADA / PROCESO / SALIDA": "Entrada (señal de disponibilidad laboral)",
    "TRADUCCIÓN / EQUIVALENCIA": "Available / Open to work",
    "EJEMPLOS": "Perfil LinkedIn de Vladisystems",
    "CATEGORÍA": "Perfil Profesional",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Footer",
    "DEFINICIÓN": "Sección ubicada al pie de cada página de un sitio web. Contiene información de contacto, enlaces secundarios, créditos, redes sociales y datos legales como políticas de privacidad.",
    "CARACTERÍSTICAS": "Presente en todas las páginas; complementa la navegación principal. Limitación: suele ser la sección menos visitada, por lo que contenido crítico no debe estar solo aquí.",
    "ENTORNO": "UI web, diseño, navegación",
    "ENTRADA / PROCESO / SALIDA": "Salida (información de referencia)",
    "TRADUCCIÓN / EQUIVALENCIA": "Footer / Pie de página",
    "EJEMPLOS": "Footer del portfolio Vladisystems con enlace a WhatsApp",
    "CATEGORÍA": "UI / UX",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Fundador",
    "DEFINICIÓN": "Persona que crea y establece una empresa, proyecto o sistema desde su concepción. Asume el liderazgo inicial, define la visión y estructura del negocio.",
    "CARACTERÍSTICAS": "Rol de liderazgo y visión estratégica. Combina habilidades técnicas, comerciales y de gestión. Limitación: el fundador único puede convertirse en cuello de botella si no delega correctamente.",
    "ENTORNO": "Startups, emprendimiento, negocios",
    "ENTRADA / PROCESO / SALIDA": "Inicio (creación del proyecto)",
    "TRADUCCIÓN / EQUIVALENCIA": "Founder / Co-founder",
    "EJEMPLOS": "Fundador de Vladisystems",
    "CATEGORÍA": "Perfil Profesional",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Gerente general",
    "DEFINICIÓN": "Responsable de la dirección, coordinación y control total de las operaciones de una empresa. Toma decisiones estratégicas y vela por el cumplimiento de objetivos organizacionales.",
    "CARACTERÍSTICAS": "Visión global del negocio, liderazgo de equipos y gestión de recursos. Limitación: la toma de decisiones centralizada puede ralentizar la operación en empresas en crecimiento.",
    "ENTORNO": "Empresa, administración, dirección ejecutiva",
    "ENTRADA / PROCESO / SALIDA": "Proceso (control y dirección total)",
    "TRADUCCIÓN / EQUIVALENCIA": "General manager / CEO (Chief Executive Officer)",
    "EJEMPLOS": "Gerente general en TULABIAL",
    "CATEGORÍA": "Perfil Profesional",
    "NIVEL TÉCNICO": "Intermedio"
  },
  {
    "TÉRMINO": "GitHub",
    "DEFINICIÓN": "Plataforma web para alojar, versionar y colaborar en proyectos de código fuente. Utiliza Git como sistema de control de versiones, permitiendo rastrear cambios, colaborar en equipo y publicar repositorios públicos o privados.",
    "CARACTERÍSTICAS": "Estándar de la industria para gestión de código. Facilita colaboración y documentación técnica. Limitación: la curva de aprendizaje inicial puede ser alta para perfiles no técnicos; los repositorios públicos exponen el código a cualquiera.",
    "ENTORNO": "Desarrollo de software, DevOps, open source",
    "ENTRADA / PROCESO / SALIDA": "Entrada (código fuente) / Salida (repositorios publicados)",
    "TRADUCCIÓN / EQUIVALENCIA": "GitHub / Git repository / Repositorio de código",
    "EJEMPLOS": "Repositorios de proyectos Vladisystems",
    "CATEGORÍA": "Plataformas y Servicios",
    "NIVEL TÉCNICO": "Intermedio"
  },
  {
    "TÉRMINO": "Grid",
    "DEFINICIÓN": "Sistema de diseño que organiza el contenido visual en filas y columnas, creando una estructura ordenada y alineada. En CSS, Grid Layout es una tecnología nativa que permite diseñar layouts complejos sin frameworks externos.",
    "CARACTERÍSTICAS": "Genera orden visual, facilita el diseño responsive y acelera el desarrollo. Estándar moderno de CSS. Limitación: requiere conocimiento técnico para implementar correctamente; puede generar inconsistencias en navegadores muy antiguos.",
    "ENTORNO": "UI, CSS, diseño frontend",
    "ENTRADA / PROCESO / SALIDA": "Proceso (organización visual)",
    "TRADUCCIÓN / EQUIVALENCIA": "Grid / CSS Grid / Layout grid / Cuadrícula",
    "EJEMPLOS": "Layout de páginas del portfolio Vladisystems",
    "CATEGORÍA": "UI / UX",
    "NIVEL TÉCNICO": "Intermedio"
  },
  {
    "TÉRMINO": "Grid lines",
    "DEFINICIÓN": "Líneas visuales decorativas que conforman el fondo de cuadrícula de una interfaz. Aportan profundidad técnica y orden visual sin ser elementos funcionales del contenido.",
    "CARACTERÍSTICAS": "Elemento puramente estético que refuerza el estilo visual técnico del diseño. Limitación: en exceso pueden distraer del contenido principal; deben tener bajo contraste con el fondo.",
    "ENTORNO": "UI, diseño visual, branding",
    "ENTRADA / PROCESO / SALIDA": "Salida (elemento visual decorativo)",
    "TRADUCCIÓN / EQUIVALENCIA": "Grid lines / Background grid / Cuadrícula de fondo",
    "EJEMPLOS": "Fondo del portfolio Vladisystems",
    "CATEGORÍA": "UI / UX",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Header",
    "DEFINICIÓN": "Sección superior de una página web que contiene el logotipo de la marca, el menú de navegación principal y en algunos casos, llamadas a la acción destacadas. Es lo primero que el usuario ve al cargar la página.",
    "CARACTERÍSTICAS": "Elemento de navegación crítico. Debe ser claro, consistente en todas las páginas y adaptarse a móvil. Limitación: un header sobrecargado confunde al usuario; menos es más en términos de opciones.",
    "ENTORNO": "UI web, navegación, branding",
    "ENTRADA / PROCESO / SALIDA": "Entrada (primer punto de orientación del usuario)",
    "TRADUCCIÓN / EQUIVALENCIA": "Header / Navigation bar / Barra de navegación",
    "EJEMPLOS": "Header del portfolio Vladisystems con menú principal",
    "CATEGORÍA": "UI / UX",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Híbrido",
    "DEFINICIÓN": "Modalidad de trabajo que combina presencia física en oficina y trabajo remoto en distintos porcentajes según acuerdo laboral. Define la flexibilidad geográfica del profesional.",
    "CARACTERÍSTICAS": "Modelo laboral moderno con alta demanda post-pandemia. Ofrece equilibrio entre colaboración presencial y autonomía remota. Limitación: requiere buena gestión del tiempo y comunicación digital efectiva.",
    "ENTORNO": "Trabajo, recursos humanos, modalidades laborales",
    "ENTRADA / PROCESO / SALIDA": "Entorno (condición laboral)",
    "TRADUCCIÓN / EQUIVALENCIA": "Hybrid work / Remote-hybrid",
    "EJEMPLOS": "Perfil laboral de Vladisystems",
    "CATEGORÍA": "Perfil Profesional",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "HTTPS",
    "DEFINICIÓN": "Protocolo de comunicación segura utilizado en internet para transferir datos entre el navegador del usuario y el servidor web. Cifra la información mediante TLS/SSL, protegiendo datos sensibles como contraseñas y pagos.",
    "CARACTERÍSTICAS": "Estándar obligatorio para cualquier sitio web moderno. Mejora el posicionamiento SEO y genera confianza en el usuario (candado verde en el navegador). Limitación: el certificado debe renovarse periódicamente; si caduca, el navegador muestra advertencia de seguridad.",
    "ENTORNO": "Internet, seguridad web, navegadores",
    "ENTRADA / PROCESO / SALIDA": "Proceso (transferencia segura de datos)",
    "TRADUCCIÓN / EQUIVALENCIA": "HyperText Transfer Protocol Secure / Protocolo de Transferencia de Hipertexto Seguro",
    "EJEMPLOS": "https://vladisystems.com",
    "CATEGORÍA": "Tecnología Web",
    "NIVEL TÉCNICO": "Intermedio"
  },
  {
    "TÉRMINO": "Lead",
    "DEFINICIÓN": "Contacto o persona que ha mostrado interés en un producto o servicio y ha proporcionado alguna forma de contacto. Es el primer paso del funnel de ventas: un prospecto que aún no se ha convertido en cliente.",
    "CARACTERÍSTICAS": "Insumo fundamental de cualquier proceso comercial digital. Puede generarse mediante formularios, WhatsApp, llamadas o redes sociales. Limitación: un lead sin seguimiento rápido se enfría y se pierde; requiere un CRM para gestionarlos correctamente.",
    "ENTORNO": "Marketing digital, CRM, ventas",
    "ENTRADA / PROCESO / SALIDA": "Entrada (inicio del proceso comercial)",
    "TRADUCCIÓN / EQUIVALENCIA": "Lead / Prospecto / Cliente potencial",
    "EJEMPLOS": "Leads generados por BC1166 y Portal33 vía WhatsApp",
    "CATEGORÍA": "Negocio / CRM",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "LinkedIn",
    "DEFINICIÓN": "Red social profesional para publicar experiencia laboral, conectar con colegas, buscar empleo y generar oportunidades de negocio. Es el estándar global de CV online.",
    "CARACTERÍSTICAS": "Alta visibilidad ante reclutadores y clientes potenciales. Permite publicar proyectos y recomendaciones. Limitación: el algoritmo favorece publicaciones frecuentes; perfiles inactivos tienen poca visibilidad.",
    "ENTORNO": "Networking profesional, recursos humanos, branding personal",
    "ENTRADA / PROCESO / SALIDA": "Entrada/Salida (perfil profesional y conexiones)",
    "TRADUCCIÓN / EQUIVALENCIA": "LinkedIn / Professional network / Red profesional",
    "EJEMPLOS": "Perfil LinkedIn de Vladisystems",
    "CATEGORÍA": "Plataformas y Servicios",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Links & Perfiles",
    "DEFINICIÓN": "Sección del portfolio que agrupa los accesos directos a perfiles profesionales externos del autor: LinkedIn, Workana, GitHub, CV descargable y otros. Centraliza la identidad digital del profesional.",
    "CARACTERÍSTICAS": "Facilita al visitante acceder a información complementaria sin salir del sitio. Limitación: los enlaces externos deben mantenerse actualizados; un link roto daña la credibilidad.",
    "ENTORNO": "UI, portfolio, networking",
    "ENTRADA / PROCESO / SALIDA": "Salida (acceso a perfiles externos)",
    "TRADUCCIÓN / EQUIVALENCIA": "Links & Profiles / External links / Perfiles y enlaces",
    "EJEMPLOS": "Sección Links del portfolio Vladisystems",
    "CATEGORÍA": "UI / UX",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Mapa del sitio",
    "DEFINICIÓN": "Representación visual o estructural de todas las páginas y secciones de un sitio web y sus relaciones jerárquicas. En el portfolio de Vladisystems se implementa como un SVG interactivo con overlay.",
    "CARACTERÍSTICAS": "Mejora la orientación del usuario y permite entender la arquitectura del sitio de un vistazo. También existe en formato XML para buscadores (SEO). Limitación: si el sitio crece sin actualizar el mapa, se vuelve confuso o desactualizado.",
    "ENTORNO": "UX, navegación, SEO",
    "ENTRADA / PROCESO / SALIDA": "Proceso (orientación y navegación) → Salida (estructura visual)",
    "TRADUCCIÓN / EQUIVALENCIA": "Site map / Sitemap / Mapa de navegación",
    "EJEMPLOS": "SVG interactivo con overlay en el portfolio Vladisystems",
    "CATEGORÍA": "UI / UX",
    "NIVEL TÉCNICO": "Intermedio"
  },
  {
    "TÉRMINO": "Master Menu",
    "DEFINICIÓN": "Sistema digital para restaurantes que centraliza el menú, permite reservas online y gestiona pedidos desde el mismo canal digital. Proyecto del portfolio de Vladisystems.",
    "CARACTERÍSTICAS": "Combina catálogo digital con funcionalidad de reservas y pedidos. Elimina la necesidad de cartas físicas. Limitación: requiere mantenimiento continuo del menú y conexión estable a internet en el restaurante.",
    "ENTORNO": "Restaurantes, hostelería, comercio digital",
    "ENTRADA / PROCESO / SALIDA": "Entrada (pedido/reserva) → Proceso (gestión) → Salida (confirmación)",
    "TRADUCCIÓN / EQUIVALENCIA": "Master Menu / Digital restaurant system / Sistema digital de restaurantes",
    "EJEMPLOS": "Proyecto del portfolio Vladisystems",
    "CATEGORÍA": "Proyectos",
    "NIVEL TÉCNICO": "Intermedio"
  },
  {
    "TÉRMINO": "Mentor",
    "DEFINICIÓN": "Persona con experiencia que guía, aconseja y transfiere conocimiento a otra persona en proceso de formación o desarrollo profesional. El mentor no solo enseña; también inspira y abre puertas.",
    "CARACTERÍSTICAS": "Relación de alto valor en procesos de aprendizaje técnico y crecimiento profesional. Limitación: la efectividad depende de la compatibilidad entre mentor y mentoreado, y del compromiso de ambas partes.",
    "ENTORNO": "Educación, formación profesional, tecnología",
    "ENTRADA / PROCESO / SALIDA": "Proceso (transferencia de conocimiento)",
    "TRADUCCIÓN / EQUIVALENCIA": "Mentor / Coach / Tutor profesional",
    "EJEMPLOS": "Vladisystems como mentor de programación",
    "CATEGORÍA": "Perfil Profesional",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Navegación",
    "DEFINICIÓN": "Sistema que permite al usuario moverse entre las distintas secciones y páginas de un sitio web. Incluye menús, botones, enlaces y elementos interactivos que guían la experiencia del visitante.",
    "CARACTERÍSTICAS": "Una navegación clara reduce la tasa de rebote y mejora la experiencia de usuario. Debe ser intuitiva y consistente. Limitación: una navegación sobrecargada o poco clara pierde al usuario en segundos.",
    "ENTORNO": "UI, UX, diseño web",
    "ENTRADA / PROCESO / SALIDA": "Entrada (acción del usuario) → Proceso (transición entre páginas)",
    "TRADUCCIÓN / EQUIVALENCIA": "Navigation / Web navigation / Navegación web",
    "EJEMPLOS": "Menú principal del portfolio Vladisystems",
    "CATEGORÍA": "UI / UX",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Overlay",
    "DEFINICIÓN": "Capa visual semitransparente que se superpone sobre el contenido principal de la página para mostrar información adicional, mapas, modales o menús contextuales sin navegar a otra página.",
    "CARACTERÍSTICAS": "Mejora la usabilidad al presentar información sin interrumpir el flujo de navegación. Limitación: mal implementado puede bloquear el contenido o ser difícil de cerrar en móviles.",
    "ENTORNO": "UI, diseño frontend, JavaScript",
    "ENTRADA / PROCESO / SALIDA": "Proceso (presentación contextual)",
    "TRADUCCIÓN / EQUIVALENCIA": "Overlay / Modal / Capa superpuesta",
    "EJEMPLOS": "Overlay del mapa del sitio en el portfolio Vladisystems",
    "CATEGORÍA": "UI / UX",
    "NIVEL TÉCNICO": "Intermedio"
  },
  {
    "TÉRMINO": "Perfil profesional",
    "DEFINICIÓN": "Resumen condensado de la experiencia, habilidades, proyectos y propuesta de valor de un profesional. Aparece en plataformas como LinkedIn, Workana o en la sección 'Sobre mí' de un portfolio.",
    "CARACTERÍSTICAS": "Primer impacto ante reclutadores o clientes. Debe ser claro, honesto y diferenciador. Limitación: un perfil genérico no se distingue entre cientos de candidatos similares.",
    "ENTORNO": "LinkedIn, portfolio, recursos humanos",
    "ENTRADA / PROCESO / SALIDA": "Salida (presentación profesional)",
    "TRADUCCIÓN / EQUIVALENCIA": "Professional profile / Personal brand / Marca personal",
    "EJEMPLOS": "Perfil LinkedIn y sección 'Sobre mí' de Vladisystems",
    "CATEGORÍA": "Perfil Profesional",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Portfolio",
    "DEFINICIÓN": "Sitio web o documento que presenta de forma estructurada y visual los proyectos, habilidades y trayectoria profesional de una persona o empresa. Funciona como carta de presentación digital activa.",
    "CARACTERÍSTICAS": "Demuestra capacidades con evidencia real en lugar de solo describirlas. Genera confianza y diferenciación. Limitación: un portfolio desactualizado o con proyectos poco documentados pierde su efectividad como herramienta comercial.",
    "ENTORNO": "Web personal, branding, desarrollo web",
    "ENTRADA / PROCESO / SALIDA": "Salida (presentación profesional con evidencia)",
    "TRADUCCIÓN / EQUIVALENCIA": "Portfolio / Digital portfolio / Portafolio profesional",
    "EJEMPLOS": "Vladisystems Portfolio (vladisystems.com)",
    "CATEGORÍA": "Identidad y Portfolio",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Portal33",
    "DEFINICIÓN": "Portal inmobiliario digital desarrollado por Vladisystems. Presenta catálogo de propiedades, genera leads comerciales y conecta potenciales compradores o arrendatarios con el equipo de ventas.",
    "CARACTERÍSTICAS": "Combina catálogo visual de propiedades con sistema de captación de leads. Limitación: depende de la actualización continua del inventario de propiedades para mantener relevancia.",
    "ENTORNO": "Real estate, marketing digital, web",
    "ENTRADA / PROCESO / SALIDA": "Entrada (visita) → Proceso (exploración de propiedades) → Salida (lead comercial)",
    "TRADUCCIÓN / EQUIVALENCIA": "Portal33 / Real estate portal / Portal inmobiliario",
    "EJEMPLOS": "Proyecto del portfolio Vladisystems",
    "CATEGORÍA": "Proyectos",
    "NIVEL TÉCNICO": "Intermedio"
  },
  {
    "TÉRMINO": "Professional Network",
    "DEFINICIÓN": "Red de contactos profesionales construida en plataformas como LinkedIn, a través de eventos o proyectos colaborativos. Permite acceder a oportunidades laborales, referencias y nuevos clientes.",
    "CARACTERÍSTICAS": "Activo intangible de alto valor a largo plazo. Cuanto mayor y más diversa sea la red, más oportunidades genera. Limitación: una red grande sin interacciones reales se vuelve superficial y poco efectiva.",
    "ENTORNO": "LinkedIn, networking, carrera profesional",
    "ENTRADA / PROCESO / SALIDA": "Proceso (construcción de relaciones) → Salida (oportunidades)",
    "TRADUCCIÓN / EQUIVALENCIA": "Professional network / Red de contactos profesionales",
    "EJEMPLOS": "LinkedIn de Vladisystems",
    "CATEGORÍA": "Plataformas y Servicios",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Programador",
    "DEFINICIÓN": "Profesional que escribe, prueba y mantiene código fuente para crear software, aplicaciones o sistemas informáticos. Transforma especificaciones lógicas en instrucciones ejecutables por un computador.",
    "CARACTERÍSTICAS": "Perfil técnico altamente demandado. Domina lenguajes de programación, algoritmos y estructuras de datos. Limitación: la especialización en un solo lenguaje puede limitar la empleabilidad a largo plazo.",
    "ENTORNO": "TI, software, desarrollo de sistemas",
    "ENTRADA / PROCESO / SALIDA": "Proceso (escritura y mantenimiento de código)",
    "TRADUCCIÓN / EQUIVALENCIA": "Programmer / Developer / Software developer / Desarrollador de software",
    "EJEMPLOS": "COBOL, JavaScript, HTML/CSS en Vladisystems",
    "CATEGORÍA": "Perfil Profesional",
    "NIVEL TÉCNICO": "Avanzado"
  },
  {
    "TÉRMINO": "Project card",
    "DEFINICIÓN": "Componente visual de UI que presenta la información resumida de un proyecto: nombre, descripción breve, tecnologías usadas y enlace de acceso. Son los bloques que conforman la sección de proyectos del portfolio.",
    "CARACTERÍSTICAS": "Modular, reutilizable y escalable. Permite agregar nuevos proyectos sin rediseñar la página. Limitación: si todos los proyectos se presentan igual, pueden perder individualidad visual.",
    "ENTORNO": "UI, portfolio, diseño frontend",
    "ENTRADA / PROCESO / SALIDA": "Salida (presentación visual de proyecto)",
    "TRADUCCIÓN / EQUIVALENCIA": "Project card / Tarjeta de proyecto",
    "EJEMPLOS": "Cards de BC1166, Portal33, VladCRM en el portfolio",
    "CATEGORÍA": "UI / UX",
    "NIVEL TÉCNICO": "Intermedio"
  },
  {
    "TÉRMINO": "Proyectos",
    "DEFINICIÓN": "Sección principal del portfolio que lista y detalla los sistemas y trabajos digitales desarrollados por Vladisystems. Cada proyecto incluye descripción, tecnologías, objetivos y enlace al sistema.",
    "CARACTERÍSTICAS": "Corazón del portfolio; es la evidencia concreta de las capacidades técnicas y comerciales. Limitación: sin documentación de calidad (capturas, demos, descripciones claras), los proyectos no comunican su verdadero valor.",
    "ENTORNO": "Portfolio, web UI, marketing profesional",
    "ENTRADA / PROCESO / SALIDA": "Salida (evidencia de trabajo realizado)",
    "TRADUCCIÓN / EQUIVALENCIA": "Projects section / Work portfolio / Portafolio de trabajos",
    "EJEMPLOS": "Sección Proyectos de Vladisystems",
    "CATEGORÍA": "Identidad y Portfolio",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Real estate",
    "DEFINICIÓN": "Sector de actividad económica relacionado con la compraventa, arriendo y gestión de bienes inmuebles (propiedades, terrenos, edificios). En el contexto digital incluye portales, CRM inmobiliarios y automatización de captación.",
    "CARACTERÍSTICAS": "Sector de alta demanda con ciclos económicos propios. Se beneficia enormemente de la digitalización. Limitación: muy sensible a factores externos como tasas de interés, regulaciones y economía local.",
    "ENTORNO": "Mercado inmobiliario, bienes raíces, economía",
    "ENTRADA / PROCESO / SALIDA": "Industria (contexto)",
    "TRADUCCIÓN / EQUIVALENCIA": "Real estate / Bienes raíces / Sector inmobiliario",
    "EJEMPLOS": "Portal33, BC1166, Team Realty History",
    "CATEGORÍA": "Negocio / CRM",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Real Systems",
    "DEFINICIÓN": "Concepto central del branding de Vladisystems que diferencia sus proyectos de ejercicios académicos o demos: son sistemas digitales reales, funcionales, con clientes reales y resultados medibles.",
    "CARACTERÍSTICAS": "Propuesta de valor de marca. Define el posicionamiento técnico y comercial. Limitación: implica un alto estándar de calidad que exige mantenimiento y documentación constante de cada proyecto.",
    "ENTORNO": "Branding, portfolio, identidad digital",
    "ENTRADA / PROCESO / SALIDA": "Concepto de marca",
    "TRADUCCIÓN / EQUIVALENCIA": "Real Systems / Sistemas reales / Soluciones digitales funcionales",
    "EJEMPLOS": "Tagline del portfolio Vladisystems",
    "CATEGORÍA": "Identidad y Portfolio",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Responsive design",
    "DEFINICIÓN": "Enfoque de diseño y desarrollo web que hace que una página se adapte automáticamente al tamaño y resolución de la pantalla del dispositivo que la visualiza, sin necesidad de crear versiones separadas del sitio.",
    "CARACTERÍSTICAS": "Estándar obligatorio desde 2015 aproximadamente. Google penaliza sitios no responsivos en su ranking. Mejora la experiencia en móviles y tablets. Limitación: puede aumentar la complejidad del CSS; algunos elementos son difíciles de adaptar bien a todos los tamaños; incompatible con navegadores muy antiguos.",
    "ENTORNO": "Frontend, CSS, diseño web",
    "ENTRADA / PROCESO / SALIDA": "Proceso (adaptación automática del layout)",
    "TRADUCCIÓN / EQUIVALENCIA": "Responsive design / Responsive web design / Diseño adaptable / Diseño responsivo",
    "EJEMPLOS": "Todos los proyectos del portfolio Vladisystems",
    "CATEGORÍA": "Tecnología Web",
    "NIVEL TÉCNICO": "Intermedio"
  },
  {
    "TÉRMINO": "SEO",
    "DEFINICIÓN": "Conjunto de técnicas y estrategias aplicadas a un sitio web para mejorar su posición en los resultados orgánicos (no pagados) de buscadores como Google. Incluye optimización técnica, de contenido y de autoridad externa.",
    "CARACTERÍSTICAS": "Genera tráfico orgánico de alta intención sin costo por clic. Resultados a largo plazo y sostenibles. Limitación: los resultados toman tiempo (meses); los algoritmos de Google cambian sin aviso; no hay garantías de posicionamiento.",
    "ENTORNO": "Marketing digital, web, motores de búsqueda",
    "ENTRADA / PROCESO / SALIDA": "Proceso (optimización para visibilidad)",
    "TRADUCCIÓN / EQUIVALENCIA": "Search Engine Optimization / Optimización para Motores de Búsqueda",
    "EJEMPLOS": "SEO local para Bogotá en proyectos de Vladisystems",
    "CATEGORÍA": "Tecnología Web",
    "NIVEL TÉCNICO": "Intermedio"
  },
  {
    "TÉRMINO": "SEO local",
    "DEFINICIÓN": "Variante del SEO enfocada en posicionar un negocio en búsquedas geográficamente relevantes. Optimiza la presencia en Google Maps, Google Business Profile y búsquedas con intención local.",
    "CARACTERÍSTICAS": "Muy efectivo para negocios con presencia física o servicios en zonas específicas. Limitación: competencia alta en ciudades grandes como Bogotá; requiere reseñas constantes y actualización del perfil de negocio.",
    "ENTORNO": "Marketing local, Google Maps, negocios presenciales",
    "ENTRADA / PROCESO / SALIDA": "Proceso (posicionamiento local)",
    "TRADUCCIÓN / EQUIVALENCIA": "Local SEO / Posicionamiento local en buscadores",
    "EJEMPLOS": "SEO local Bogotá para clientes de Vladisystems",
    "CATEGORÍA": "Tecnología Web",
    "NIVEL TÉCNICO": "Intermedio"
  },
  {
    "TÉRMINO": "Tailwind CSS",
    "DEFINICIÓN": "Framework de CSS utilitario que proporciona clases predefinidas de bajo nivel para construir interfaces directamente en el HTML, sin necesidad de escribir CSS personalizado desde cero.",
    "CARACTERÍSTICAS": "Acelera el desarrollo frontend, garantiza consistencia visual y facilita el diseño responsive. Altamente personalizable. Limitación: el HTML puede volverse verbose con muchas clases; curva de aprendizaje inicial si se viene de CSS tradicional.",
    "ENTORNO": "Frontend, diseño web, desarrollo UI",
    "ENTRADA / PROCESO / SALIDA": "Proceso (estilización de interfaces)",
    "TRADUCCIÓN / EQUIVALENCIA": "Tailwind CSS / CSS utility framework / Framework CSS de utilidades",
    "EJEMPLOS": "Usado en proyectos del portfolio Vladisystems",
    "CATEGORÍA": "Tecnología Web",
    "NIVEL TÉCNICO": "Intermedio"
  },
  {
    "TÉRMINO": "Team Realty History",
    "DEFINICIÓN": "Portal inmobiliario narrativo desarrollado por Vladisystems que combina storytelling con presentación de propiedades, diferenciándose de los portales tradicionales mediante historias y contexto emocional.",
    "CARACTERÍSTICAS": "Innovador en el sector inmobiliario. Usa el relato como herramienta de marketing. Limitación: requiere producción de contenido narrativo constante, lo que demanda tiempo y habilidades de redacción.",
    "ENTORNO": "Real estate, marketing de contenidos, storytelling",
    "ENTRADA / PROCESO / SALIDA": "Salida (marketing narrativo inmobiliario)",
    "TRADUCCIÓN / EQUIVALENCIA": "Team Realty History / Narrative real estate portal / Portal inmobiliario narrativo",
    "EJEMPLOS": "Proyecto del portfolio Vladisystems",
    "CATEGORÍA": "Proyectos",
    "NIVEL TÉCNICO": "Intermedio"
  },
  {
    "TÉRMINO": "Telegram Bot",
    "DEFINICIÓN": "Programa automatizado que opera dentro de la plataforma Telegram. Puede responder mensajes, enviar notificaciones, ejecutar comandos y conectarse con otras APIs, sin intervención humana continua.",
    "CARACTERÍSTICAS": "Potente herramienta de automatización y comunicación. Puede integrar IA para respuestas inteligentes. Limitación: su funcionalidad está limitada a la plataforma Telegram; si el usuario no usa Telegram, no tiene acceso.",
    "ENTORNO": "Mensajería, automatización, IA",
    "ENTRADA / PROCESO / SALIDA": "Proceso (interacción automática)",
    "TRADUCCIÓN / EQUIVALENCIA": "Telegram Bot / Automated messaging bot / Bot de mensajería automatizada",
    "EJEMPLOS": "Telegram Bot Vladiblues (Vladisystems)",
    "CATEGORÍA": "Proyectos",
    "NIVEL TÉCNICO": "Avanzado"
  },
  {
    "TÉRMINO": "UI",
    "DEFINICIÓN": "Disciplina y conjunto de elementos visuales e interactivos con los que el usuario interactúa directamente en una aplicación o sitio web: botones, menús, formularios, tipografías, colores e íconos.",
    "CARACTERÍSTICAS": "Define la primera impresión del producto digital. Un buen UI atrae y retiene usuarios. Limitación: un UI visualmente atractivo sin UX sólida genera frustración; ambas deben diseñarse en conjunto.",
    "ENTORNO": "Diseño web, aplicaciones, desarrollo frontend",
    "ENTRADA / PROCESO / SALIDA": "Proceso (diseño y presentación visual)",
    "TRADUCCIÓN / EQUIVALENCIA": "User Interface / Interfaz de Usuario",
    "EJEMPLOS": "Diseño UI del portfolio Vladisystems",
    "CATEGORÍA": "UI / UX",
    "NIVEL TÉCNICO": "Intermedio"
  },
  {
    "TÉRMINO": "UX",
    "DEFINICIÓN": "Disciplina que estudia y optimiza la experiencia completa de un usuario al interactuar con un producto o servicio digital. Va más allá de lo visual: abarca usabilidad, arquitectura de información, flujos y emociones del usuario.",
    "CARACTERÍSTICAS": "Define qué tan fácil, eficiente y satisfactorio es el uso del producto. Un buen UX reduce la tasa de abandono. Limitación: difícil de medir objetivamente; requiere pruebas con usuarios reales para validar.",
    "ENTORNO": "Diseño de producto, web, aplicaciones",
    "ENTRADA / PROCESO / SALIDA": "Proceso (optimización de la experiencia del usuario)",
    "TRADUCCIÓN / EQUIVALENCIA": "User Experience / Experiencia de Usuario",
    "EJEMPLOS": "Flujos de navegación y estructura del portfolio Vladisystems",
    "CATEGORÍA": "UI / UX",
    "NIVEL TÉCNICO": "Intermedio"
  },
  {
    "TÉRMINO": "VladCRM",
    "DEFINICIÓN": "Sistema de gestión de clientes (CRM) desarrollado internamente por Vladisystems para automatizar el seguimiento de leads, gestión de contactos y flujos comerciales propios.",
    "CARACTERÍSTICAS": "Sistema a medida que responde exactamente a las necesidades del negocio Vladisystems. Elimina la dependencia de herramientas de terceros costosas. Limitación: requiere mantenimiento propio y no tiene soporte externo.",
    "ENTORNO": "CRM, negocios, automatización comercial",
    "ENTRADA / PROCESO / SALIDA": "Proceso (gestión automatizada de clientes)",
    "TRADUCCIÓN / EQUIVALENCIA": "VladCRM / Custom CRM / CRM propio / Sistema de gestión de clientes",
    "EJEMPLOS": "Proyecto del portfolio Vladisystems",
    "CATEGORÍA": "Proyectos",
    "NIVEL TÉCNICO": "Avanzado"
  },
  {
    "TÉRMINO": "Web system",
    "DEFINICIÓN": "Sistema de software accesible a través de un navegador web estándar, sin necesidad de instalación local. Los datos y la lógica residen en servidores remotos y se presentan en interfaz HTML/CSS/JS.",
    "CARACTERÍSTICAS": "Accesible desde cualquier dispositivo con conexión a internet. Fácil de actualizar centralmente. Limitación: requiere conectividad; el rendimiento depende del servidor y la velocidad de la red del usuario.",
    "ENTORNO": "Internet, desarrollo web, software",
    "ENTRADA / PROCESO / SALIDA": "Proceso (acceso y uso del sistema)",
    "TRADUCCIÓN / EQUIVALENCIA": "Web system / Web application / Sistema web / Aplicación web",
    "EJEMPLOS": "Portfolio Vladisystems, BC1166, VladCRM",
    "CATEGORÍA": "Tecnología Web",
    "NIVEL TÉCNICO": "Intermedio"
  },
  {
    "TÉRMINO": "WhatsApp",
    "DEFINICIÓN": "Plataforma de mensajería instantánea de Meta ampliamente utilizada en Colombia y Latinoamérica para comunicación personal y comercial. En contextos de negocio, es el canal de contacto directo más efectivo para cerrar leads.",
    "CARACTERÍSTICAS": "Alta tasa de apertura y respuesta comparada con email. Canal preferido en mercados latinoamericanos. Limitación: sin automatización, el manejo de múltiples conversaciones comerciales se vuelve caótico; los mensajes se pueden perder.",
    "ENTORNO": "Mensajería, comunicación, marketing digital",
    "ENTRADA / PROCESO / SALIDA": "Entrada (contacto comercial inicial)",
    "TRADUCCIÓN / EQUIVALENCIA": "WhatsApp / Instant messaging / Mensajería instantánea",
    "EJEMPLOS": "Botón WhatsApp en BC1166, Portal33, portfolio",
    "CATEGORÍA": "Plataformas y Servicios",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "WhatsApp conversion",
    "DEFINICIÓN": "Proceso de convertir una visita o interacción web en un contacto directo por WhatsApp. Es el último paso del funnel de captación en varios proyectos de Vladisystems: el usuario hace clic y abre una conversación comercial.",
    "CARACTERÍSTICAS": "Métricamente efectivo en mercados donde WhatsApp es el canal dominante. Tasa de conversión superior al email o formulario. Limitación: depende de que el usuario tenga WhatsApp instalado y activo.",
    "ENTORNO": "Marketing digital, CRM, ventas",
    "ENTRADA / PROCESO / SALIDA": "Salida (conversión comercial)",
    "TRADUCCIÓN / EQUIVALENCIA": "WhatsApp conversion / WhatsApp lead / Conversión por WhatsApp",
    "EJEMPLOS": "BC1166 y Portal33 usan link wa.me como CTA principal",
    "CATEGORÍA": "Negocio / CRM",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Workana",
    "DEFINICIÓN": "Plataforma de trabajo freelance latinoamericana que conecta profesionales independientes con clientes que necesitan servicios digitales. Permite publicar proyectos, recibir propuestas y contratar talento.",
    "CARACTERÍSTICAS": "Canal de captación de proyectos freelance con alta actividad en Colombia. Limitación: alta competencia y comisión de la plataforma sobre los ingresos; no reemplaza al portfolio propio para posicionamiento de marca.",
    "ENTORNO": "Freelance, trabajo remoto, servicios digitales",
    "ENTRADA / PROCESO / SALIDA": "Entrada/Salida (proyectos y servicios)",
    "TRADUCCIÓN / EQUIVALENCIA": "Workana / Freelance platform / Plataforma freelance",
    "EJEMPLOS": "Perfil Workana de Vladisystems",
    "CATEGORÍA": "Plataformas y Servicios",
    "NIVEL TÉCNICO": "Básico"
  },
   {
    "TÉRMINO": "Backend",
    "DEFINICIÓN": "Parte de una aplicación o sitio web que se ejecuta en el servidor y que el usuario no ve directamente. Gestiona la lógica de negocio, el acceso a bases de datos, la seguridad y la comunicación con el frontend a través de APIs.",
    "CARACTERÍSTICAS": "Procesa datos, valida información y ejecuta reglas de negocio; requiere lenguajes como Node.js, Python, PHP o Java. Limitación: si falla, toda la aplicación pierde funcionalidad aunque la interfaz se vea normal.",
    "ENTORNO": "Desarrollo de software, servidores",
    "ENTRADA / PROCESO / SALIDA": "Proceso (lógica del servidor)",
    "TRADUCCIÓN / EQUIVALENCIA": "Lógica del servidor / Lado del servidor",
    "EJEMPLOS": "API de VladCRM construida en Node.js",
    "CATEGORÍA": "Desarrollo de Software",
    "NIVEL TÉCNICO": "Intermedio"
  },
  {
    "TÉRMINO": "Frontend",
    "DEFINICIÓN": "Parte de una aplicación o sitio web con la que el usuario interactúa directamente en el navegador. Incluye el diseño visual, la maquetación y el comportamiento de los elementos de la interfaz.",
    "CARACTERÍSTICAS": "Construido con HTML, CSS y JavaScript o frameworks como React; debe ser responsive y rápido. Limitación: depende del backend para mostrar datos reales.",
    "ENTORNO": "Desarrollo de software, interfaces web",
    "ENTRADA / PROCESO / SALIDA": "Salida (interfaz visible al usuario)",
    "TRADUCCIÓN / EQUIVALENCIA": "Interfaz de usuario / Lado del cliente",
    "EJEMPLOS": "Interfaz visual del Portal33",
    "CATEGORÍA": "Desarrollo de Software",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "API",
    "DEFINICIÓN": "Conjunto de reglas y protocolos que permite que dos sistemas o aplicaciones se comuniquen entre sí, enviando y recibiendo datos de forma estandarizada sin que cada sistema necesite conocer el funcionamiento interno del otro.",
    "CARACTERÍSTICAS": "Permite integrar servicios externos (pagos, mensajería, mapas); suele usar formato JSON. Limitación: depende de la disponibilidad y los límites de uso del proveedor.",
    "ENTORNO": "Integraciones de software, desarrollo web",
    "ENTRADA / PROCESO / SALIDA": "Proceso (comunicación entre sistemas)",
    "TRADUCCIÓN / EQUIVALENCIA": "Interfaz de Programación de Aplicaciones",
    "EJEMPLOS": "API de WhatsApp Business integrada en Telegram Bot",
    "CATEGORÍA": "Desarrollo de Software",
    "NIVEL TÉCNICO": "Intermedio"
  },
  {
    "TÉRMINO": "Framework",
    "DEFINICIÓN": "Conjunto de herramientas, librerías y reglas predefinidas que sirve como base estructural para construir aplicaciones de forma más rápida y ordenada, evitando escribir código repetitivo desde cero.",
    "CARACTERÍSTICAS": "Impone una estructura y buenas prácticas; acelera el desarrollo. Limitación: agrega una curva de aprendizaje y depende de actualizaciones del proveedor.",
    "ENTORNO": "Desarrollo de software",
    "ENTRADA / PROCESO / SALIDA": "Proceso (estructura para construir el sistema)",
    "TRADUCCIÓN / EQUIVALENCIA": "Marco de trabajo",
    "EJEMPLOS": "Tailwind CSS como framework de estilos en Real Systems",
    "CATEGORÍA": "Desarrollo de Software",
    "NIVEL TÉCNICO": "Intermedio"
  },
  {
    "TÉRMINO": "Repository",
    "DEFINICIÓN": "Espacio de almacenamiento donde se guarda el código fuente de un proyecto junto con el historial completo de cambios realizados sobre él a lo largo del tiempo.",
    "CARACTERÍSTICAS": "Permite control de versiones y trabajo colaborativo; puede ser público o privado. Limitación: requiere disciplina en el versionado para evitar conflictos.",
    "ENTORNO": "Control de versiones, desarrollo de software",
    "ENTRADA / PROCESO / SALIDA": "Entrada / Salida (almacenamiento de código)",
    "TRADUCCIÓN / EQUIVALENCIA": "Repositorio",
    "EJEMPLOS": "Repositorio de VladCRM en GitHub",
    "CATEGORÍA": "Desarrollo de Software",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Commit",
    "DEFINICIÓN": "Acción de guardar un conjunto de cambios realizados en el código dentro del historial de un repositorio, junto con un mensaje descriptivo que explica qué se modificó.",
    "CARACTERÍSTICAS": "Cada commit queda registrado con autor, fecha y descripción; permite revertir cambios. Limitación: mensajes poco claros dificultan el seguimiento del historial.",
    "ENTORNO": "Control de versiones",
    "ENTRADA / PROCESO / SALIDA": "Proceso (registro de cambios)",
    "TRADUCCIÓN / EQUIVALENCIA": "Confirmación de cambios",
    "EJEMPLOS": "Commit con la corrección del formulario de contacto",
    "CATEGORÍA": "Desarrollo de Software",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Push",
    "DEFINICIÓN": "Acción de enviar los commits guardados localmente hacia un repositorio remoto, para que los cambios queden disponibles para el resto del equipo o para el servidor de producción.",
    "CARACTERÍSTICAS": "Sincroniza el trabajo local con la nube; suele activar procesos de despliegue automático. Limitación: puede generar conflictos si otros ya modificaron el mismo archivo.",
    "ENTORNO": "Control de versiones",
    "ENTRADA / PROCESO / SALIDA": "Salida (envío de cambios al repositorio remoto)",
    "TRADUCCIÓN / EQUIVALENCIA": "Subir cambios / Empujar cambios",
    "EJEMPLOS": "Push de la nueva versión del sitio a GitHub",
    "CATEGORÍA": "Desarrollo de Software",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Pull",
    "DEFINICIÓN": "Acción de descargar y aplicar los cambios más recientes de un repositorio remoto hacia la copia local del proyecto, para mantenerla actualizada con el trabajo de otros colaboradores.",
    "CARACTERÍSTICAS": "Mantiene sincronizado el entorno local; suele combinarse con la revisión de conflictos. Limitación: si hay cambios locales sin guardar, puede generar conflictos.",
    "ENTORNO": "Control de versiones",
    "ENTRADA / PROCESO / SALIDA": "Entrada (descarga de cambios remotos)",
    "TRADUCCIÓN / EQUIVALENCIA": "Descargar cambios / Traer cambios",
    "EJEMPLOS": "Pull de la rama principal antes de empezar a trabajar",
    "CATEGORÍA": "Desarrollo de Software",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Branch",
    "DEFINICIÓN": "Línea de desarrollo independiente dentro de un repositorio que permite trabajar en nuevas funciones o correcciones sin afectar la versión principal del proyecto hasta que los cambios estén listos.",
    "CARACTERÍSTICAS": "Facilita el trabajo en paralelo entre varios desarrolladores; se fusiona con la rama principal mediante un merge. Limitación: ramas muy desactualizadas generan conflictos al integrarlas.",
    "ENTORNO": "Control de versiones",
    "ENTRADA / PROCESO / SALIDA": "Proceso (línea de desarrollo paralela)",
    "TRADUCCIÓN / EQUIVALENCIA": "Rama",
    "EJEMPLOS": "Branch 'feature-dashboard' en el repositorio de VladCRM",
    "CATEGORÍA": "Desarrollo de Software",
    "NIVEL TÉCNICO": "Intermedio"
  },
  {
    "TÉRMINO": "Hosting",
    "DEFINICIÓN": "Servicio que ofrece el espacio y la infraestructura técnica necesarios para que un sitio web o aplicación esté disponible y accesible permanentemente en internet.",
    "CARACTERÍSTICAS": "Incluye almacenamiento, ancho de banda y soporte técnico; varía entre compartido, VPS o en la nube. Limitación: un hosting de baja calidad afecta la velocidad y disponibilidad del sitio.",
    "ENTORNO": "Infraestructura web",
    "ENTRADA / PROCESO / SALIDA": "Salida (disponibilidad del sitio en internet)",
    "TRADUCCIÓN / EQUIVALENCIA": "Alojamiento web",
    "EJEMPLOS": "Hosting en la nube para el sitio de Real Systems",
    "CATEGORÍA": "Desarrollo de Software",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Domain",
    "DEFINICIÓN": "Nombre único y fácil de recordar que identifica a un sitio web en internet, reemplazando la dirección numérica del servidor (IP) por un texto legible para las personas.",
    "CARACTERÍSTICAS": "Debe registrarse y renovarse periódicamente; puede tener distintas extensiones (.com, .co, .net). Limitación: si no se renueva a tiempo, se pierde el acceso al sitio.",
    "ENTORNO": "Infraestructura web",
    "ENTRADA / PROCESO / SALIDA": "Entrada (identificador de acceso al sitio)",
    "TRADUCCIÓN / EQUIVALENCIA": "Dominio",
    "EJEMPLOS": "Dominio vladisystems.com",
    "CATEGORÍA": "Desarrollo de Software",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Server",
    "DEFINICIÓN": "Computadora o sistema remoto que almacena, procesa y entrega datos o servicios a otros dispositivos (clientes) que se conectan a través de una red, generalmente internet.",
    "CARACTERÍSTICAS": "Permanece encendido y disponible de forma continua; puede ser físico o virtual. Limitación: una caída del servidor deja inaccesible todo lo que depende de él.",
    "ENTORNO": "Infraestructura, desarrollo de software",
    "ENTRADA / PROCESO / SALIDA": "Proceso (procesamiento y entrega de datos)",
    "TRADUCCIÓN / EQUIVALENCIA": "Servidor",
    "EJEMPLOS": "Servidor donde corre la API de VladCRM",
    "CATEGORÍA": "Desarrollo de Software",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Database",
    "DEFINICIÓN": "Conjunto organizado de datos almacenados de forma estructurada, que permite guardar, consultar, modificar y eliminar información de manera eficiente mediante un sistema gestor.",
    "CARACTERÍSTICAS": "Puede ser relacional (tablas, SQL) o no relacional (documentos, NoSQL); requiere respaldo y seguridad. Limitación: un diseño deficiente afecta el rendimiento a medida que crecen los datos.",
    "ENTORNO": "Desarrollo de software, gestión de datos",
    "ENTRADA / PROCESO / SALIDA": "Entrada / Salida (almacenamiento y consulta de datos)",
    "TRADUCCIÓN / EQUIVALENCIA": "Base de datos",
    "EJEMPLOS": "Base de datos de clientes y leads en VladCRM",
    "CATEGORÍA": "Desarrollo de Software",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Cloud",
    "DEFINICIÓN": "Modelo de entrega de servicios informáticos (almacenamiento, procesamiento, software) a través de internet, sin necesidad de tener servidores físicos propios instalados en una oficina.",
    "CARACTERÍSTICAS": "Permite escalar recursos según la demanda y pagar solo por lo que se usa; facilita el acceso remoto. Limitación: depende totalmente de la conexión a internet.",
    "ENTORNO": "Infraestructura tecnológica",
    "ENTRADA / PROCESO / SALIDA": "Proceso (provisión de recursos bajo demanda)",
    "TRADUCCIÓN / EQUIVALENCIA": "Nube",
    "EJEMPLOS": "Almacenamiento en la nube de los archivos de proyectos",
    "CATEGORÍA": "Desarrollo de Software",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Fullstack",
    "DEFINICIÓN": "Capacidad de un desarrollador de trabajar tanto en el frontend (interfaz visible) como en el backend (lógica del servidor) de una aplicación, cubriendo todas las capas del desarrollo.",
    "CARACTERÍSTICAS": "Requiere conocimientos amplios en varias tecnologías; útil en equipos pequeños o proyectos independientes. Limitación: puede tener menor profundidad de especialización que un perfil enfocado en una sola capa.",
    "ENTORNO": "Desarrollo de software",
    "ENTRADA / PROCESO / SALIDA": "Proceso (desarrollo integral de la aplicación)",
    "TRADUCCIÓN / EQUIVALENCIA": "Desarrollador integral (frontend + backend)",
    "EJEMPLOS": "Desarrollador fullstack a cargo de VladCRM y su interfaz",
    "CATEGORÍA": "Desarrollo de Software",
    "NIVEL TÉCNICO": "Intermedio"
  },
  {
    "TÉRMINO": "DevOps",
    "DEFINICIÓN": "Conjunto de prácticas culturales y técnicas que integran el desarrollo de software (Dev) y la operación de sistemas (Ops), automatizando procesos de prueba, integración y despliegue para entregar software más rápido y con mayor calidad.",
    "CARACTERÍSTICAS": "Usa automatización, integración continua (CI/CD) y monitoreo constante. Limitación: requiere cambio cultural en el equipo, no solo herramientas.",
    "ENTORNO": "Desarrollo y operaciones de software",
    "ENTRADA / PROCESO / SALIDA": "Proceso (integración y entrega continua)",
    "TRADUCCIÓN / EQUIVALENCIA": "Desarrollo y Operaciones",
    "EJEMPLOS": "Pipeline de DevOps para desplegar automáticamente el Portal33",
    "CATEGORÍA": "Desarrollo de Software",
    "NIVEL TÉCNICO": "Avanzado"
  },
  {
    "TÉRMINO": "Batch",
    "DEFINICIÓN": "Forma de procesamiento en la que un conjunto de operaciones o programas se ejecuta de manera automática y secuencial, sin intervención del usuario, generalmente sobre grandes volúmenes de datos.",
    "CARACTERÍSTICAS": "Se programa para ejecutarse en horarios específicos (por ejemplo, de madrugada); procesa miles o millones de registros. Limitación: los resultados no son inmediatos, a diferencia del procesamiento en línea.",
    "ENTORNO": "Mainframe, sistemas legacy, programación COBOL",
    "ENTRADA / PROCESO / SALIDA": "Proceso (ejecución masiva y automática)",
    "TRADUCCIÓN / EQUIVALENCIA": "Proceso por lotes",
    "EJEMPLOS": "Proceso batch nocturno de liquidación bancaria",
    "CATEGORÍA": "Programación COBOL",
    "NIVEL TÉCNICO": "Avanzado"
  },
  {
    "TÉRMINO": "Mainframe",
    "DEFINICIÓN": "Computador central de gran capacidad, utilizado por grandes organizaciones para procesar enormes volúmenes de transacciones y datos de forma confiable, segura y continua, típicamente bancos, aseguradoras y gobiernos.",
    "CARACTERÍSTICAS": "Ofrece altísima disponibilidad, seguridad y capacidad de procesamiento paralelo; suele ejecutar COBOL, JCL, CICS y DB2. Limitación: su mantenimiento y licenciamiento tienen un costo elevado.",
    "ENTORNO": "Sistemas legacy, banca, seguros, gobierno",
    "ENTRADA / PROCESO / SALIDA": "Proceso (procesamiento centralizado de alto volumen)",
    "TRADUCCIÓN / EQUIVALENCIA": "Computador central / Equipo central",
    "EJEMPLOS": "Sistema bancario corriendo sobre un mainframe IBM",
    "CATEGORÍA": "Programación COBOL",
    "NIVEL TÉCNICO": "Avanzado"
  },
  {
    "TÉRMINO": "JCL",
    "DEFINICIÓN": "Lenguaje utilizado en sistemas mainframe para indicarle al sistema operativo qué programas ejecutar, en qué orden, con qué archivos de entrada y salida, y con qué recursos.",
    "CARACTERÍSTICAS": "Se organiza en pasos (steps) y declaraciones DD; controla la ejecución de programas COBOL y procesos batch. Limitación: errores de sintaxis en el JCL impiden que el trabajo se ejecute (ABEND).",
    "ENTORNO": "Mainframe, sistemas legacy",
    "ENTRADA / PROCESO / SALIDA": "Proceso (control de ejecución de trabajos)",
    "TRADUCCIÓN / EQUIVALENCIA": "Lenguaje de Control de Trabajos (Job Control Language)",
    "EJEMPLOS": "JCL que ejecuta el programa de cierre contable mensual",
    "CATEGORÍA": "Programación COBOL",
    "NIVEL TÉCNICO": "Avanzado"
  },
  {
    "TÉRMINO": "DB2",
    "DEFINICIÓN": "Sistema gestor de bases de datos relacionales desarrollado por IBM, utilizado principalmente en entornos mainframe para almacenar y consultar grandes volúmenes de información empresarial mediante SQL.",
    "CARACTERÍSTICAS": "Se integra con programas COBOL a través de SQL embebido; ofrece alto rendimiento y confiabilidad transaccional. Limitación: requiere personal especializado para su administración y sintonización.",
    "ENTORNO": "Mainframe, gestión de bases de datos",
    "ENTRADA / PROCESO / SALIDA": "Entrada / Salida (almacenamiento y consulta de datos)",
    "TRADUCCIÓN / EQUIVALENCIA": "Sistema de gestión de bases de datos de IBM",
    "EJEMPLOS": "Tabla de clientes consultada desde un programa COBOL con DB2",
    "CATEGORÍA": "Programación COBOL",
    "NIVEL TÉCNICO": "Avanzado"
  },
  {
    "TÉRMINO": "CICS",
    "DEFINICIÓN": "Sistema de IBM que permite ejecutar transacciones en línea sobre mainframe, gestionando múltiples solicitudes de usuarios en tiempo real y coordinando el acceso a programas y datos de forma simultánea.",
    "CARACTERÍSTICAS": "Cada transacción se identifica con un nombre (TRANSID) y crea una tarea asociada; soporta miles de usuarios concurrentes. Limitación: requiere conocimientos especializados para el diseño de transacciones.",
    "ENTORNO": "Mainframe, procesamiento transaccional en línea",
    "ENTRADA / PROCESO / SALIDA": "Proceso (gestión de transacciones en línea)",
    "TRADUCCIÓN / EQUIVALENCIA": "Sistema de Control de Información de Clientes (Customer Information Control System)",
    "EJEMPLOS": "Transacción CICS de consulta de saldo bancario",
    "CATEGORÍA": "Programación COBOL",
    "NIVEL TÉCNICO": "Avanzado"
  },
  {
    "TÉRMINO": "Copybook",
    "DEFINICIÓN": "Archivo independiente que contiene definiciones de datos o bloques de código COBOL reutilizables, los cuales se incorporan a uno o varios programas mediante la instrucción COPY, evitando duplicar la misma estructura en cada uno.",
    "CARACTERÍSTICAS": "Centraliza estructuras de datos compartidas (como registros de clientes); cualquier cambio exige recompilar los programas que lo usan. Limitación: modificar un copybook sin control de impacto puede romper múltiples programas.",
    "ENTORNO": "Programación COBOL, mainframe",
    "ENTRADA / PROCESO / SALIDA": "Entrada (definición de estructura de datos reutilizable)",
    "TRADUCCIÓN / EQUIVALENCIA": "Librería de copia / Plantilla de estructura de datos",
    "EJEMPLOS": "Copybook CUSTMAST con la estructura del registro de clientes",
    "CATEGORÍA": "Programación COBOL",
    "NIVEL TÉCNICO": "Avanzado"
  },
  {
    "TÉRMINO": "Working-Storage",
    "DEFINICIÓN": "Sección de un programa COBOL donde se declaran las variables, contadores y estructuras de datos que el programa utilizará temporalmente durante su ejecución, sin estar ligadas directamente a un archivo externo.",
    "CARACTERÍSTICAS": "Forma parte de la DATA DIVISION; los valores definidos aquí pueden inicializarse desde el propio código. Limitación: el espacio declarado aquí se reserva en memoria durante toda la ejecución del programa.",
    "ENTORNO": "Programación COBOL",
    "ENTRADA / PROCESO / SALIDA": "Proceso (declaración de variables de trabajo)",
    "TRADUCCIÓN / EQUIVALENCIA": "Sección de almacenamiento de trabajo",
    "EJEMPLOS": "WORKING-STORAGE SECTION con la variable WS-MESSAGE",
    "CATEGORÍA": "Programación COBOL",
    "NIVEL TÉCNICO": "Avanzado"
  },
  {
    "TÉRMINO": "Paragraph",
    "DEFINICIÓN": "Bloque de instrucciones identificado por un nombre dentro de la PROCEDURE DIVISION de un programa COBOL, que agrupa una secuencia de acciones relacionadas y puede ser invocado desde otras partes del programa.",
    "CARACTERÍSTICAS": "Se ejecuta mediante instrucciones como PERFORM; ayuda a organizar la lógica en módulos lógicos. Limitación: un uso desordenado de párrafos dificulta la lectura y el mantenimiento del programa.",
    "ENTORNO": "Programación COBOL",
    "ENTRADA / PROCESO / SALIDA": "Proceso (bloque de lógica ejecutable)",
    "TRADUCCIÓN / EQUIVALENCIA": "Párrafo (bloque de instrucciones)",
    "EJEMPLOS": "Párrafo A000-MAIN-PARA que controla el flujo principal del programa",
    "CATEGORÍA": "Programación COBOL",
    "NIVEL TÉCNICO": "Avanzado"
  },
  {
    "TÉRMINO": "Section",
    "DEFINICIÓN": "Subdivisión estructural dentro de una división de un programa COBOL (como DATA DIVISION o PROCEDURE DIVISION) que agrupa elementos relacionados, como variables o párrafos, bajo un mismo propósito.",
    "CARACTERÍSTICAS": "Cada división puede contener varias secciones (FILE SECTION, WORKING-STORAGE SECTION); organiza el programa jerárquicamente. Limitación: el orden y la sintaxis de las secciones son rígidos y deben respetarse estrictamente.",
    "ENTORNO": "Programación COBOL",
    "ENTRADA / PROCESO / SALIDA": "Proceso (organización estructural del programa)",
    "TRADUCCIÓN / EQUIVALENCIA": "Sección",
    "EJEMPLOS": "FILE SECTION donde se describen los archivos de entrada y salida",
    "CATEGORÍA": "Programación COBOL",
    "NIVEL TÉCNICO": "Avanzado"
  },
  {
    "TÉRMINO": "Program-ID",
    "DEFINICIÓN": "Cláusula obligatoria al inicio de un programa COBOL, dentro de la IDENTIFICATION DIVISION, que asigna un nombre único al programa, el cual se utiliza para identificarlo, compilarlo y ejecutarlo dentro del sistema.",
    "CARACTERÍSTICAS": "Es la primera instrucción significativa de cualquier programa COBOL; el nombre suele seguir convenciones del sitio o empresa. Limitación: el nombre debe coincidir con el usado en el JCL y en los procesos de compilación.",
    "ENTORNO": "Programación COBOL",
    "ENTRADA / PROCESO / SALIDA": "Entrada (identificación del programa)",
    "TRADUCCIÓN / EQUIVALENCIA": "Identificador de programa",
    "EJEMPLOS": "PROGRAM-ID. HELLO. al inicio de un programa COBOL",
    "CATEGORÍA": "Programación COBOL",
    "NIVEL TÉCNICO": "Avanzado"
  },
  {
    "TÉRMINO": "Conversión",
    "DEFINICIÓN": "Acción específica que realiza un usuario y que la empresa considera valiosa para su negocio, como completar una compra, dejar sus datos de contacto o agendar una cita, dentro de un proceso digital de marketing o ventas.",
    "CARACTERÍSTICAS": "Se mide mediante una tasa de conversión (porcentaje de visitantes que completan la acción); puede ocurrir en distintas etapas del embudo. Limitación: una tasa baja puede indicar problemas en la oferta, el mensaje o la experiencia de usuario.",
    "ENTORNO": "Marketing digital, negocio digital",
    "ENTRADA / PROCESO / SALIDA": "Salida (resultado del proceso de captación)",
    "TRADUCCIÓN / EQUIVALENCIA": "Conversion",
    "EJEMPLOS": "Conversión de WhatsApp a cliente en Real Systems",
    "CATEGORÍA": "Negocio Digital",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Funnel",
    "DEFINICIÓN": "Representación del recorrido que sigue una persona desde que conoce una marca o producto hasta que se convierte en cliente, dividido en etapas como atracción, interés, decisión y acción.",
    "CARACTERÍSTICAS": "Cada etapa tiene menos personas que la anterior, de ahí su forma de embudo; permite identificar en qué punto se pierden los prospectos. Limitación: un embudo mal diseñado puede perder leads valiosos en etapas intermedias.",
    "ENTORNO": "Marketing digital, ventas",
    "ENTRADA / PROCESO / SALIDA": "Proceso (recorrido del cliente hacia la compra)",
    "TRADUCCIÓN / EQUIVALENCIA": "Funnel / Embudo de conversión",
    "EJEMPLOS": "Funnel de captación de leads inmobiliarios en VladCRM",
    "CATEGORÍA": "Negocio Digital",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "KPI",
    "DEFINICIÓN": "Métrica concreta y medible que se utiliza para evaluar el desempeño de una estrategia, proceso o equipo en relación con un objetivo específico previamente definido por el negocio.",
    "CARACTERÍSTICAS": "Debe ser específico, medible y relevante para la meta del negocio; se revisa periódicamente en dashboards. Limitación: elegir KPIs irrelevantes lleva a decisiones basadas en datos que no reflejan el objetivo real.",
    "ENTORNO": "Gestión empresarial, marketing digital",
    "ENTRADA / PROCESO / SALIDA": "Salida (indicador de resultado)",
    "TRADUCCIÓN / EQUIVALENCIA": "Indicador Clave de Rendimiento (Key Performance Indicator)",
    "EJEMPLOS": "KPI de leads generados al mes en el Dashboard de VladCRM",
    "CATEGORÍA": "Negocio Digital",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "ROI",
    "DEFINICIÓN": "Indicador financiero que mide la ganancia o pérdida generada por una inversión en relación con su costo, expresado normalmente como porcentaje, y que permite evaluar si una estrategia o proyecto fue rentable.",
    "CARACTERÍSTICAS": "Se calcula como (beneficio obtenido - costo de la inversión) dividido entre el costo de la inversión; se usa para justificar presupuestos. Limitación: no siempre captura beneficios intangibles como reputación de marca.",
    "ENTORNO": "Negocio digital, finanzas, marketing",
    "ENTRADA / PROCESO / SALIDA": "Salida (resultado financiero de una inversión)",
    "TRADUCCIÓN / EQUIVALENCIA": "Retorno de la Inversión (Return On Investment)",
    "EJEMPLOS": "ROI de una campaña de captación de clientes inmobiliarios",
    "CATEGORÍA": "Negocio Digital",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Prospecto",
    "DEFINICIÓN": "Persona o empresa que muestra un interés inicial en un producto o servicio y que, por sus características, tiene potencial de convertirse en cliente, aunque todavía no haya tomado una decisión de compra.",
    "CARACTERÍSTICAS": "Se encuentra en una etapa temprana del embudo de ventas, antes de calificar como lead avanzado; requiere seguimiento comercial. Limitación: no todo prospecto avanza hacia la conversión.",
    "ENTORNO": "Ventas, negocio digital, CRM",
    "ENTRADA / PROCESO / SALIDA": "Entrada (potencial cliente identificado)",
    "TRADUCCIÓN / EQUIVALENCIA": "Prospect / Lead potencial",
    "EJEMPLOS": "Prospecto registrado en VladCRM tras llenar un formulario",
    "CATEGORÍA": "Negocio Digital",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Visibilidad",
    "DEFINICIÓN": "Grado en que una marca, producto o contenido es percibido, encontrado y reconocido por su público objetivo en los distintos canales digitales donde este se encuentra.",
    "CARACTERÍSTICAS": "Se logra mediante SEO, redes sociales, publicidad y presencia constante; es la base para generar tráfico y, eventualmente, conversiones. Limitación: alta visibilidad sin una propuesta clara no garantiza conversiones.",
    "ENTORNO": "Marketing digital, branding",
    "ENTRADA / PROCESO / SALIDA": "Salida (alcance y exposición de la marca)",
    "TRADUCCIÓN / EQUIVALENCIA": "Visibility",
    "EJEMPLOS": "Visibilidad en buscadores gracias al SEO local de Real Systems",
    "CATEGORÍA": "Negocio Digital",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Monetización",
    "DEFINICIÓN": "Proceso de convertir una audiencia, un producto, un servicio o una plataforma digital en una fuente de ingresos económicos, mediante distintos modelos como venta directa, suscripciones o publicidad.",
    "CARACTERÍSTICAS": "Puede aplicarse a contenidos, aplicaciones o bases de datos de clientes; requiere una estrategia clara de modelo de negocio. Limitación: monetizar demasiado pronto o de forma agresiva puede afectar la experiencia del usuario.",
    "ENTORNO": "Negocio digital, modelos de ingresos",
    "ENTRADA / PROCESO / SALIDA": "Proceso (transformación de valor en ingresos)",
    "TRADUCCIÓN / EQUIVALENCIA": "Monetization",
    "EJEMPLOS": "Monetización de la plataforma VladCRM mediante planes de suscripción",
    "CATEGORÍA": "Negocio Digital",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Negocio",
    "DEFINICIÓN": "Actividad organizada que ofrece productos o servicios a un mercado con el fin de generar ingresos y valor, sosteniéndose a través de una propuesta clara dirigida a un público específico.",
    "CARACTERÍSTICAS": "Requiere una propuesta de valor, un mercado objetivo y un modelo de ingresos definido. Limitación: sin una estrategia clara de captación, un negocio puede no ser sostenible en el tiempo.",
    "ENTORNO": "Gestión empresarial, negocio digital",
    "ENTRADA / PROCESO / SALIDA": "Proceso (actividad económica organizada)",
    "TRADUCCIÓN / EQUIVALENCIA": "Business",
    "EJEMPLOS": "Negocio inmobiliario gestionado a través de Real Systems",
    "CATEGORÍA": "Negocio Digital",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Sistemas",
    "DEFINICIÓN": "Conjunto de elementos tecnológicos —software, hardware, datos y procesos— que trabajan de forma coordinada para cumplir una función específica dentro de una organización, como gestionar información o automatizar tareas.",
    "CARACTERÍSTICAS": "Pueden ser de gestión, comunicación o automatización; suelen integrarse entre sí mediante APIs. Limitación: sistemas mal integrados generan duplicidad de información y errores operativos.",
    "ENTORNO": "Tecnología, gestión empresarial",
    "ENTRADA / PROCESO / SALIDA": "Proceso (conjunto coordinado de componentes tecnológicos)",
    "TRADUCCIÓN / EQUIVALENCIA": "Systems",
    "EJEMPLOS": "Sistema de gestión de clientes VladCRM",
    "CATEGORÍA": "Tecnología Web",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Marketing",
    "DEFINICIÓN": "Conjunto de estrategias y acciones orientadas a entender las necesidades de un público objetivo y comunicar el valor de un producto o servicio, con el fin de atraer, captar y retener clientes.",
    "CARACTERÍSTICAS": "Incluye canales digitales y tradicionales (redes sociales, SEO, publicidad, branding); se apoya en KPIs para medir resultados. Limitación: sin una estrategia clara, la inversión en marketing puede no traducirse en conversiones.",
    "ENTORNO": "Negocio digital, comunicación comercial",
    "ENTRADA / PROCESO / SALIDA": "Proceso (atracción y retención de clientes)",
    "TRADUCCIÓN / EQUIVALENCIA": "Marketing",
    "EJEMPLOS": "Estrategia de marketing digital para captar leads inmobiliarios",
    "CATEGORÍA": "Negocio Digital",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Inmobiliaria",
    "DEFINICIÓN": "Sector económico y empresarial dedicado a la compra, venta, arriendo y administración de propiedades como casas, apartamentos, locales y terrenos, generalmente a través de agentes o plataformas especializadas.",
    "CARACTERÍSTICAS": "Depende del comportamiento del mercado, las tasas de interés y la oferta disponible; cada vez incorpora más herramientas digitales para la gestión de clientes. Limitación: es un sector sensible a ciclos económicos.",
    "ENTORNO": "Sector inmobiliario, bienes raíces",
    "ENTRADA / PROCESO / SALIDA": "Proceso (gestión de propiedades y transacciones)",
    "TRADUCCIÓN / EQUIVALENCIA": "Real estate (sector)",
    "EJEMPLOS": "Gestión de propiedades a través de Team Realty History",
    "CATEGORÍA": "Negocio Digital",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Branding",
    "DEFINICIÓN": "Proceso de construir y gestionar la identidad de una marca —su nombre, valores, personalidad visual y forma de comunicarse— con el objetivo de generar reconocimiento y confianza en su público.",
    "CARACTERÍSTICAS": "Incluye logotipo, paleta de colores, tono de comunicación y experiencia de marca; debe mantenerse consistente en todos los canales. Limitación: un branding inconsistente debilita la confianza y el reconocimiento de la marca.",
    "ENTORNO": "Identidad de marca, marketing",
    "ENTRADA / PROCESO / SALIDA": "Proceso (construcción de identidad de marca)",
    "TRADUCCIÓN / EQUIVALENCIA": "Branding / Construcción de marca",
    "EJEMPLOS": "Branding aplicado al portafolio de Vladisystems",
    "CATEGORÍA": "Identidad y Portfolio",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "Tecnología",
    "DEFINICIÓN": "Conjunto de conocimientos, técnicas y herramientas aplicadas para resolver problemas, automatizar procesos o crear productos y servicios, abarcando desde el desarrollo de software hasta la infraestructura digital.",
    "CARACTERÍSTICAS": "Evoluciona constantemente; abarca hardware, software, redes y datos. Limitación: requiere actualización permanente para no quedar obsoleta frente a nuevas soluciones.",
    "ENTORNO": "Desarrollo de software, infraestructura digital",
    "ENTRADA / PROCESO / SALIDA": "Proceso (aplicación de conocimiento técnico)",
    "TRADUCCIÓN / EQUIVALENCIA": "Technology",
    "EJEMPLOS": "Tecnología utilizada en el desarrollo del Portal33",
    "CATEGORÍA": "Tecnología Web",
    "NIVEL TÉCNICO": "Básico"
  },
  {
    "TÉRMINO": "BigQuery",
    "DEFINICIÓN": "Almacén de datos (data warehouse) en la nube de Google Cloud, completamente administrado y sin servidores, que permite almacenar y analizar grandes volúmenes de datos mediante consultas en SQL estándar, sin necesidad de gestionar infraestructura propia.",
    "CARACTERÍSTICAS": "Separa el almacenamiento del procesamiento para escalar de forma independiente; procesa consultas sobre petabytes de datos en segundos y soporta machine learning integrado (BigQuery ML). Limitación: el modelo de pago por uso puede generar costos variables si no se controlan los volúmenes de consulta.",
    "ENTORNO": "Análisis de datos, Google Cloud Platform",
    "ENTRADA / PROCESO / SALIDA": "Proceso (almacenamiento y análisis de grandes volúmenes de datos)",
    "TRADUCCIÓN / EQUIVALENCIA": "Almacén de datos en la nube de Google",
    "EJEMPLOS": "Análisis de datos de clientes de VladCRM exportados a BigQuery",
    "CATEGORÍA": "Tecnología Web",
    "NIVEL TÉCNICO": "Avanzado"
  },
  {
    "TÉRMINO": "Power BI",
    "DEFINICIÓN": "Plataforma de inteligencia de negocios (Business Intelligence) de Microsoft que permite conectar, transformar y visualizar datos provenientes de múltiples fuentes para crear informes y paneles interactivos que faciliten la toma de decisiones.",
    "CARACTERÍSTICAS": "Se compone principalmente de Power BI Desktop (creación de informes) y el servicio Power BI en la nube (publicación y colaboración); usa el lenguaje DAX para cálculos y Power Query para transformar datos. Limitación: el modelado avanzado y el lenguaje DAX tienen una curva de aprendizaje para usuarios sin experiencia previa en análisis de datos.",
    "ENTORNO": "Inteligencia de negocios, análisis de datos, Microsoft 365",
    "ENTRADA / PROCESO / SALIDA": "Proceso (transformación y visualización de datos)",
    "TRADUCCIÓN / EQUIVALENCIA": "Plataforma de Inteligencia de Negocios de Microsoft",
    "EJEMPLOS": "Dashboard de ventas inmobiliarias construido en Power BI a partir de datos de VladCRM",
    "CATEGORÍA": "Tecnología Web",
    "NIVEL TÉCNICO": "Avanzado"
  },
]
